:toc: macro
:toclevels: 5
:figure-caption!:

:trmnl_link: link:https://usetrmnl.com[TRMNL]
:ror_link: link:https://rubyonrails.org[Ruby on Rails]
:i18n_link: link:https://guides.rubyonrails.org/i18n.html[I18n]

= TRMNL I18n

This is the complete collection of locales for {trmnl_link} internationalization.

toc::[]

== Contributions

Nothing needs to be installed on your computer. No coding is required. Follow link:https://github.com/usetrmnl/localizations/blob/main/GUIDE.md[the guide].

If you want to run the test suite locally, follow the steps below.

== Requirements

. link:https://www.ruby-lang.org[Ruby].
. {ror_link}.
. {trmnl_link}.

== Setup

To install _with_ security, run:

[source,bash]
----
# 💡 Skip this line if you already have the public certificate installed.
gem cert --add <(curl --compressed --location https://usetrmnl.com/gems.pem)
gem install trmnl-i18n --trust-policy HighSecurity
----

To install _without_ security, run:

[source,bash]
----
gem install trmnl-i18n
----

You can also add the gem directly to your project:

[source,bash]
----
bundle add trmnl-i18n
----

Once the gem is installed, you only need to require it:

[source,ruby]
----
require "trmnl/i18n"
----

If you are using this gem in a non-Rails application, you will need to manually load the locales during the application's initialization.

[source,ruby]
----
TRMNL::I18n.load_locales
----

== Usage

This gem is a {ror_link} Railtie that follows {i18n_link} conventions allowing you to customize country locales. You only need to include this gem, as documented in the xref:_setup[Setup] section, to automatically load and use these locales. That's it!

== Development

To contribute, run:

[source,bash]
----
git clone https://github.com/usetrmnl/trmnl-i18n
cd trmnl-i18n
bin/setup
----

You can also use the IRB console for direct access to all objects:

[source,bash]
----
bin/console
----

To add new locale  keys, first add them to the `en.yml` files in each folder. Then run `bin/sync` to update all other languages. The default source locale is always `en` but you can supply a specific locale if you like. For example, if wanting to use French as the default source locale, run: `bin/sync fr`.

To test within a Rails app for local development purposes, you can do the following:

. Create a feature branch and add your new locales.
. Push the feature branch up (no need to open a code review until you are ready).
. Update your Rails application's `Gemfile` to point to your feature branch. Example: `gem "trmnl-i18n", github: "your_fork/trmnl-i18n", branch: "your_feature_branch"`.

== Tests

To test, run:

[source,bash]
----
bin/rake
----

== Deployment

To publish, first:

. Install link:https://alchemists.io/projects/gemsmith[Gemsmith].
. link:https://alchemists.io/projects/gemsmith#_configuration[Configure] your account.
. Enable link:https://alchemists.io/projects/gemsmith#_security[security].

Once the above is setup, now you can publish by doing the following:

[source,bash]
----
git switch main
git pull
gemsmith --publish
----

That's it!

== Credits

* German via [@ramdacxp](https://github.com/ramdacxp), [@philippbosch](https://github.com/philippbosch), [@yannicschuller](https://github.com/yannicschuller), [@MaxDev98](https://github.com/MaxDev98), [@IngmarStein](https://github.com/IngmarStein), [@DavidOrtmann](https://github.com/DavidOrtmann), [@Wandmalfarbe](https://github.com/Wandmalfarbe)
* Spanish (Spain) via [@joesfer](https://github.com/joesfer), [@jeff-foster](https://github.com/jeff-foster), [@fixmycode](https://github.com/fixmycode), [@jcorbalanm](https://github.com/jcorbalanm)
* French via [@theogiraudet](https://github.com/theogiraudet), [@MarvinNTA](https://github.com/MarvinNTA)
* Indonesian via [@Adekabang](https://github.com/Adekabang)
* Icelandic via [@arnib13](https://github.com/arnib13)
* Italian via [@danieleb-podero](https://github.com/danieleb-podero), [@Stefifox](https://github.com/Stefifox)
* Japanese via Hiroyuki Miyoshi, [@liahsheep](https://github.com/liahsheep)
* Korean via [@i-say-young](https://github.com/i-say-young)
* Polish via [@EbonyBirch](https://github.com/EbonyBirch)
* Brazilian Portuguese via [@danielsitnik](https://github.com/danielsitnik)
* Danish via [@clysel](https://github.com/clysel)
* Dutch via [@huge10](https://github.com/huge10), [@SjanPjer](https://github.com/SjanPjer), [@gjdenhertog](https://github.com/gjdenhertog), [@hufman](https://github.com/hufman), [@lukasvermeer](https://github.com/lukasvermeer)
* Ukrainian via [@veikus](https://github.com/veikus), [@yankobogdan](https://github.com/yankobogdan)
* Chinese (Simplified) via [@JoshBashed](https://github.com/JoshBashed), [@MarkSong535](https://github.com/MarkSong535)
* Chinese (Hong Kong) via [@liahsheep](https://github.com/liahsheep)
* Hebrew via [@itay99988](https://github.com/itay99988)
* Russian via [@putnik](https://github.com/putnik)
* Built with link:https://alchemists.io/projects/gemsmith[Gemsmith].
* Engineered by link:https://usetrmnl.com[TRMNL].
