:toc: macro
:toclevels: 5
:figure-caption!:

:trmnl_link: link:https://usetrmnl.com[TRMNL]
:ror_link: link:https://rubyonrails.org[Ruby on Rails]
:i18n_link: link:https://guides.rubyonrails.org/i18n.html[I18n]

= TRMNL I18n

This is the complete collection locales for {trmnl_link} internationalization.

toc::[]

== Contributions

1. Fork this repository.
2. Follow the link:https://github.com/usetrmnl/localizations/blob/main/GUIDE.md[guide].

== Requirements

. link:https://www.ruby-lang.org[Ruby].
. {ror_link}.
. {trmnl_link}.

== Setup

To install _with_ security, run:

[source,bash]
----
# 💡 Skip this line if you already have the public certificate installed.
gem cert --add <(curl --compressed --location https://usetrmnl.com/gems.pem)
gem install trmnl-i18n --trust-policy HighSecurity
----

To install _without_ security, run:

[source,bash]
----
gem install trmnl-i18n
----

You can also add the gem directly to your project:

[source,bash]
----
bundle add trmnl-i18n
----

Once the gem is installed, you only need to require it:

[source,ruby]
----
require "trmnl/i18n"
----

If you are using this gem in a non-Rails application, you will need to manually load the locales during the application's initialization.

[source,ruby]
----
TRMNL::I18n.load_locales
----

== Usage

This gem is a {ror_link} Railtie that follows {i18n_link} conventions allowing you to customize country locales. You only need to include this gem, as documented in the xref:_setup[Setup] section, to automatically load and use these locales. That's it!

== Development

To contribute, run:

[source,bash]
----
git clone https://github.com/usetrmnl/trmnl-i18n
cd trmnl-i18n
bin/setup
----

You can also use the IRB console for direct access to all objects:

[source,bash]
----
bin/console
----

To add new locale  keys, first add them to the `en.yml` files in each folder. Then run `bin/sync` to update all other languages. The default source locale is always `en` but you can supply a specific locale if you like. For example, if wanting to use French as the default source locale, run: `bin/sync fr`.

To test within a Rails app for local development purposes, you can do the following:

. Create a feature branch and add your new locales.
. Push the feature branch up (no need to open a code review until you are ready).
. Update your Rails application's `Gemfile` to point to your feature branch. Example: `gem "trmnl-i18n", github: "your_fork/trmnl-i18n", branch: "your_feature_branch"`.

== Tests

To test, run:

[source,bash]
----
bin/rake
----

== Deployment

To publish, first:

. Install link:https://alchemists.io/projects/gemsmith[Gemsmith].
. link:https://alchemists.io/projects/gemsmith#_configuration[Configure] your account.
. Enable link:https://alchemists.io/projects/gemsmith#_security[security].

Once the above is setup, now you can publish by doing the following:

[source,bash]
----
git switch main
git pull
gemsmith --publish
----

That's it!

== Credits

* German via @ramdacxp, @philippbosch, @yannicschuller, @MaxDev98, @IngmarStein, @DavidOrtmann, @Wandmalfarbe
* Spanish (Spain) via @joesfer, @jeff-foster, @fixmycode, @jcorbalanm
* French via @theogiraudet, @MarvinNTA
* Indonesian via @Adekabang
* Icelandic via @arnib13
* Italian via @danieleb-podero, @Stefifox
* Japanese via Hiroyuki Miyoshi, @liahsheep
* Korean via @i-say-young
* Portuguese via @danielsitnik
* Danish via @clysel
* Dutch via @huge10, @SjanPjer, @gjdenhertog, @hufman, @lukasvermeer
* Ukrainian via @veikus, @yankobogdan
* Chinese (Simplified) via @JoshBashed, @MarkSong535
* Chinese (Hong Kong) via @liahsheep
* Hebrew via @itay99988
* Built with link:https://alchemists.io/projects/gemsmith[Gemsmith].
* Engineered by link:https://usetrmnl.com[TRMNL].
